document.writeln("<!-- 百度主动推送 -->");
document.writeln("<script>");
document.writeln("(function(){");
document.writeln("    var bp = document.createElement(\'script\');");
document.writeln("    var curProtocol = window.location.protocol.split(\':\')[0];");
document.writeln("    if (curProtocol === \'https\') {");
document.writeln("        bp.src = \'https://zz.bdstatic.com/linksubmit/push.js\';");
document.writeln("    }");
document.writeln("    else {");
document.writeln("        bp.src = \'http://push.zhanzhang.baidu.com/push.js\';");
document.writeln("    }");
document.writeln("    var s = document.getElementsByTagName(\'script\')[0];");
document.writeln("    s.parentNode.insertBefore(bp, s);");
document.writeln("})();");
document.writeln("</script>");
document.writeln("<!-- 360主动推送 -->");
document.writeln("<script>");
document.writeln("(function(){");
document.writeln("var src = \'https://jspassport.ssl.qhimg.com/11.0.1.js?d182b3f28525f2db83acfaaf6e696dba\';");
document.writeln("document.write(\'<script src=\'\' + src + \'\' id=\'sozz\'><\/\//script>\');");
document.writeln("})();");
document.writeln("</script>");
